/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "baseUrl": "/",
  "future": {
    "experimental_faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "tagline": "Powerful static analysis for JavaScript and TypeScript.",
  "title": "typescript-eslint",
  "url": "https://typescript-eslint.io",
  "clientModules": [
    "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/src/clientModules.js"
  ],
  "customFields": {
    "rules": [
      {
        "docs": {
          "description": "Require that function overload signatures be consecutive",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/adjacent-overload-signatures"
        },
        "name": "adjacent-overload-signatures",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require consistently using either `T[]` or `Array<T>` for arrays",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/array-type"
        },
        "fixable": "code",
        "name": "array-type",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow awaiting a value that is not a Thenable",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/await-thenable"
        },
        "hasSuggestions": true,
        "name": "await-thenable",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow `@ts-<directive>` comments or require descriptions after directives",
          "recommended": {
            "recommended": true,
            "strict": [
              {
                "minimumDescriptionLength": 10
              }
            ]
          },
          "url": "https://typescript-eslint.io/rules/ban-ts-comment"
        },
        "hasSuggestions": true,
        "name": "ban-ts-comment",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow `// tslint:<rule-flag>` comments",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/ban-tslint-comment"
        },
        "fixable": "code",
        "name": "ban-tslint-comment",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce that literals on classes are exposed in a consistent style",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/class-literal-property-style"
        },
        "hasSuggestions": true,
        "name": "class-literal-property-style",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Enforce that class methods utilize `this`",
          "extendsBaseRule": true,
          "requiresTypeChecking": false,
          "url": "https://typescript-eslint.io/rules/class-methods-use-this"
        },
        "name": "class-methods-use-this",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce specifying generic type arguments on type annotation or constructor name of a constructor call",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/consistent-generic-constructors"
        },
        "fixable": "code",
        "name": "consistent-generic-constructors",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require or disallow the `Record` type",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/consistent-indexed-object-style"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "consistent-indexed-object-style",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require `return` statements to either always or never specify values",
          "extendsBaseRule": true,
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/consistent-return"
        },
        "name": "consistent-return",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce consistent usage of type assertions",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/consistent-type-assertions"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "consistent-type-assertions",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce type definitions to consistently use either `interface` or `type`",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/consistent-type-definitions"
        },
        "fixable": "code",
        "name": "consistent-type-definitions",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce consistent usage of type exports",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/consistent-type-exports"
        },
        "fixable": "code",
        "name": "consistent-type-exports",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce consistent usage of type imports",
          "url": "https://typescript-eslint.io/rules/consistent-type-imports"
        },
        "fixable": "code",
        "name": "consistent-type-imports",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce default parameters to be last",
          "extendsBaseRule": true,
          "frozen": true,
          "url": "https://typescript-eslint.io/rules/default-param-last"
        },
        "name": "default-param-last",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce dot notation whenever possible",
          "extendsBaseRule": true,
          "frozen": true,
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/dot-notation"
        },
        "fixable": "code",
        "name": "dot-notation",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require explicit return types on functions and class methods",
          "url": "https://typescript-eslint.io/rules/explicit-function-return-type"
        },
        "name": "explicit-function-return-type",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require explicit accessibility modifiers on class properties and methods",
          "url": "https://typescript-eslint.io/rules/explicit-member-accessibility"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "explicit-member-accessibility",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require explicit return and argument types on exported functions' and classes' public class methods",
          "url": "https://typescript-eslint.io/rules/explicit-module-boundary-types"
        },
        "name": "explicit-module-boundary-types",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require or disallow initialization in variable declarations",
          "extendsBaseRule": true,
          "frozen": true,
          "url": "https://typescript-eslint.io/rules/init-declarations"
        },
        "name": "init-declarations",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce a maximum number of parameters in function definitions",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/max-params"
        },
        "name": "max-params",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require a consistent member declaration order",
          "frozen": true,
          "url": "https://typescript-eslint.io/rules/member-ordering"
        },
        "name": "member-ordering",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce using a particular method signature syntax",
          "url": "https://typescript-eslint.io/rules/method-signature-style"
        },
        "fixable": "code",
        "name": "method-signature-style",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce naming conventions for everything across a codebase",
          "frozen": true,
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/naming-convention"
        },
        "name": "naming-convention",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow generic `Array` constructors",
          "extendsBaseRule": true,
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-array-constructor"
        },
        "fixable": "code",
        "name": "no-array-constructor",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow using the `delete` operator on array values",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-array-delete"
        },
        "hasSuggestions": true,
        "name": "no-array-delete",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require `.toString()` and `.toLocaleString()` to only be called on objects which provide useful information when stringified",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-base-to-string"
        },
        "name": "no-base-to-string",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow non-null assertion in locations that may be confusing",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/no-confusing-non-null-assertion"
        },
        "hasSuggestions": true,
        "name": "no-confusing-non-null-assertion",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require expressions of type void to appear in statement position",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-confusing-void-expression"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "no-confusing-void-expression",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow using code marked as `@deprecated`",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-deprecated"
        },
        "name": "no-deprecated",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow duplicate class members",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-dupe-class-members"
        },
        "name": "no-dupe-class-members",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow duplicate enum member values",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-duplicate-enum-values"
        },
        "hasSuggestions": false,
        "name": "no-duplicate-enum-values",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow duplicate constituents of union or intersection types",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-duplicate-type-constituents"
        },
        "fixable": "code",
        "name": "no-duplicate-type-constituents",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow using the `delete` operator on computed key expressions",
          "recommended": "strict",
          "url": "https://typescript-eslint.io/rules/no-dynamic-delete"
        },
        "name": "no-dynamic-delete",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow empty functions",
          "extendsBaseRule": true,
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/no-empty-function"
        },
        "hasSuggestions": true,
        "name": "no-empty-function",
        "type": "suggestion"
      },
      {
        "deprecated": {
          "deprecatedSince": "8.0.0",
          "replacedBy": [
            {
              "rule": {
                "name": "@typescript-eslint/no-empty-object-type",
                "url": "https://typescript-eslint.io/rules/no-empty-object-type"
              }
            }
          ],
          "url": "https://github.com/typescript-eslint/typescript-eslint/pull/8977"
        },
        "docs": {
          "description": "Disallow the declaration of empty interfaces",
          "url": "https://typescript-eslint.io/rules/no-empty-interface"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "no-empty-interface",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow accidentally using the \"empty object\" type",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-empty-object-type"
        },
        "hasSuggestions": true,
        "name": "no-empty-object-type",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow the `any` type",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-explicit-any"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "no-explicit-any",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow extra non-null assertions",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-extra-non-null-assertion"
        },
        "fixable": "code",
        "name": "no-extra-non-null-assertion",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow classes used as namespaces",
          "recommended": "strict",
          "url": "https://typescript-eslint.io/rules/no-extraneous-class"
        },
        "name": "no-extraneous-class",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require Promise-like statements to be handled appropriately",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-floating-promises"
        },
        "hasSuggestions": true,
        "name": "no-floating-promises",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow iterating over an array with a for-in loop",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-for-in-array"
        },
        "name": "no-for-in-array",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow the use of `eval()`-like functions",
          "extendsBaseRule": true,
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-implied-eval"
        },
        "name": "no-implied-eval",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce the use of top-level import type qualifier when an import only has specifiers with inline type qualifiers",
          "url": "https://typescript-eslint.io/rules/no-import-type-side-effects"
        },
        "fixable": "code",
        "name": "no-import-type-side-effects",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow explicit type declarations for variables or parameters initialized to a number, string, or boolean",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/no-inferrable-types"
        },
        "fixable": "code",
        "name": "no-inferrable-types",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow `this` keywords outside of classes or class-like objects",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-invalid-this"
        },
        "name": "no-invalid-this",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow `void` type outside of generic or return types",
          "recommended": "strict",
          "url": "https://typescript-eslint.io/rules/no-invalid-void-type"
        },
        "name": "no-invalid-void-type",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow function declarations that contain unsafe references inside loop statements",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-loop-func"
        },
        "name": "no-loop-func",
        "type": "suggestion"
      },
      {
        "deprecated": {
          "deprecatedSince": "8.0.0",
          "replacedBy": [
            {
              "rule": {
                "name": "no-loss-of-precision",
                "url": "https://eslint.org/docs/latest/rules/no-loss-of-precision"
              }
            }
          ],
          "url": "https://github.com/typescript-eslint/typescript-eslint/pull/8832"
        },
        "docs": {
          "description": "Disallow literal numbers that lose precision",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-loss-of-precision"
        },
        "name": "no-loss-of-precision",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow magic numbers",
          "extendsBaseRule": true,
          "frozen": true,
          "url": "https://typescript-eslint.io/rules/no-magic-numbers"
        },
        "name": "no-magic-numbers",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow the `void` operator except when used to discard a value",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-meaningless-void-operator"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "no-meaningless-void-operator",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce valid definition of `new` and `constructor`",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-misused-new"
        },
        "name": "no-misused-new",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow Promises in places not designed to handle them",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-misused-promises"
        },
        "name": "no-misused-promises",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow using the spread operator when it might cause unexpected behavior",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-misused-spread"
        },
        "hasSuggestions": true,
        "name": "no-misused-spread",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow enums from having both number and string members",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-mixed-enums"
        },
        "name": "no-mixed-enums",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow TypeScript namespaces",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-namespace"
        },
        "name": "no-namespace",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow non-null assertions in the left operand of a nullish coalescing operator",
          "recommended": "strict",
          "url": "https://typescript-eslint.io/rules/no-non-null-asserted-nullish-coalescing"
        },
        "hasSuggestions": true,
        "name": "no-non-null-asserted-nullish-coalescing",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow non-null assertions after an optional chain expression",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-non-null-asserted-optional-chain"
        },
        "hasSuggestions": true,
        "name": "no-non-null-asserted-optional-chain",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow non-null assertions using the `!` postfix operator",
          "recommended": "strict",
          "url": "https://typescript-eslint.io/rules/no-non-null-assertion"
        },
        "hasSuggestions": true,
        "name": "no-non-null-assertion",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow variable redeclaration",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-redeclare"
        },
        "name": "no-redeclare",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow members of unions and intersections that do nothing or override type information",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-redundant-type-constituents"
        },
        "name": "no-redundant-type-constituents",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow invocation of `require()`",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-require-imports"
        },
        "name": "no-require-imports",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow specified modules when loaded by `import`",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-restricted-imports"
        },
        "name": "no-restricted-imports",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow certain types",
          "url": "https://typescript-eslint.io/rules/no-restricted-types"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "no-restricted-types",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow variable declarations from shadowing variables declared in the outer scope",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-shadow"
        },
        "name": "no-shadow",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow aliasing `this`",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-this-alias"
        },
        "name": "no-this-alias",
        "type": "suggestion"
      },
      {
        "deprecated": {
          "deprecatedSince": "6.0.0",
          "replacedBy": [
            {
              "rule": {
                "name": "@typescript-eslint/consistent-type-definitions",
                "url": "https://typescript-eslint.io/rules/consistent-type-definitions"
              }
            }
          ],
          "url": "https://github.com/typescript-eslint/typescript-eslint/pull/6229"
        },
        "docs": {
          "description": "Disallow type aliases",
          "url": "https://typescript-eslint.io/rules/no-type-alias"
        },
        "name": "no-type-alias",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow unnecessary equality comparisons against boolean literals",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare"
        },
        "fixable": "code",
        "name": "no-unnecessary-boolean-literal-compare",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow conditionals where the type is always truthy or always falsy",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-condition"
        },
        "hasSuggestions": true,
        "name": "no-unnecessary-condition",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow unnecessary assignment of constructor property parameter",
          "url": "https://typescript-eslint.io/rules/no-unnecessary-parameter-property-assignment"
        },
        "name": "no-unnecessary-parameter-property-assignment",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow unnecessary namespace qualifiers",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-qualifier"
        },
        "fixable": "code",
        "name": "no-unnecessary-qualifier",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow unnecessary template expressions",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-template-expression"
        },
        "fixable": "code",
        "name": "no-unnecessary-template-expression",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow type arguments that are equal to the default",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-type-arguments"
        },
        "fixable": "code",
        "name": "no-unnecessary-type-arguments",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow type assertions that do not change the type of an expression",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-type-assertion"
        },
        "fixable": "code",
        "name": "no-unnecessary-type-assertion",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow unnecessary constraints on generic types",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-unnecessary-type-constraint"
        },
        "hasSuggestions": true,
        "name": "no-unnecessary-type-constraint",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow conversion idioms when they do not change the type or value of the expression",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-type-conversion"
        },
        "hasSuggestions": true,
        "name": "no-unnecessary-type-conversion",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow type parameters that aren't used multiple times",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unnecessary-type-parameters"
        },
        "hasSuggestions": true,
        "name": "no-unnecessary-type-parameters",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow calling a function with a value with type `any`",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-argument"
        },
        "name": "no-unsafe-argument",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow assigning a value with type `any` to variables and properties",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-assignment"
        },
        "name": "no-unsafe-assignment",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow calling a value with type `any`",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-call"
        },
        "name": "no-unsafe-call",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow unsafe declaration merging",
          "recommended": "recommended",
          "requiresTypeChecking": false,
          "url": "https://typescript-eslint.io/rules/no-unsafe-declaration-merging"
        },
        "name": "no-unsafe-declaration-merging",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow comparing an enum value with a non-enum value",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-enum-comparison"
        },
        "hasSuggestions": true,
        "name": "no-unsafe-enum-comparison",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow using the unsafe built-in Function type",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-unsafe-function-type"
        },
        "name": "no-unsafe-function-type",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow member access on a value with type `any`",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-member-access"
        },
        "name": "no-unsafe-member-access",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow returning a value with type `any` from a function",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-return"
        },
        "name": "no-unsafe-return",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow type assertions that narrow a type",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-type-assertion"
        },
        "name": "no-unsafe-type-assertion",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require unary negation to take a number",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-unsafe-unary-minus"
        },
        "name": "no-unsafe-unary-minus",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow unused expressions",
          "extendsBaseRule": true,
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-unused-expressions"
        },
        "name": "no-unused-expressions",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow unused private class members",
          "extendsBaseRule": true,
          "requiresTypeChecking": false,
          "url": "https://typescript-eslint.io/rules/no-unused-private-class-members"
        },
        "name": "no-unused-private-class-members",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow unused variables",
          "extendsBaseRule": true,
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-unused-vars"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "no-unused-vars",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow the use of variables before they are defined",
          "extendsBaseRule": true,
          "url": "https://typescript-eslint.io/rules/no-use-before-define"
        },
        "name": "no-use-before-define",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow unnecessary constructors",
          "extendsBaseRule": true,
          "recommended": "strict",
          "url": "https://typescript-eslint.io/rules/no-useless-constructor"
        },
        "hasSuggestions": true,
        "name": "no-useless-constructor",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow default values that will never be used",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/no-useless-default-assignment"
        },
        "fixable": "code",
        "name": "no-useless-default-assignment",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow empty exports that don't change anything in a module file",
          "url": "https://typescript-eslint.io/rules/no-useless-empty-export"
        },
        "fixable": "code",
        "hasSuggestions": false,
        "name": "no-useless-empty-export",
        "type": "suggestion"
      },
      {
        "deprecated": {
          "deprecatedSince": "8.0.0",
          "replacedBy": [
            {
              "rule": {
                "name": "@typescript-eslint/no-require-imports",
                "url": "https://typescript-eslint.io/rules/no-require-imports"
              }
            }
          ],
          "url": "https://github.com/typescript-eslint/typescript-eslint/pull/8334"
        },
        "docs": {
          "description": "Disallow `require` statements except in import statements",
          "url": "https://typescript-eslint.io/rules/no-var-requires"
        },
        "name": "no-var-requires",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow using confusing built-in primitive class wrappers",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/no-wrapper-object-types"
        },
        "fixable": "code",
        "name": "no-wrapper-object-types",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Enforce non-null assertions over explicit type assertions",
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/non-nullable-type-assertion-style"
        },
        "fixable": "code",
        "name": "non-nullable-type-assertion-style",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow throwing non-`Error` values as exceptions",
          "extendsBaseRule": "no-throw-literal",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/only-throw-error"
        },
        "name": "only-throw-error",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require or disallow parameter properties in class constructors",
          "url": "https://typescript-eslint.io/rules/parameter-properties"
        },
        "name": "parameter-properties",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Enforce the use of `as const` over literal type",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/prefer-as-const"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "prefer-as-const",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require destructuring from arrays and/or objects",
          "extendsBaseRule": true,
          "frozen": true,
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-destructuring"
        },
        "fixable": "code",
        "name": "prefer-destructuring",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require each enum member value to be explicitly initialized",
          "url": "https://typescript-eslint.io/rules/prefer-enum-initializers"
        },
        "hasSuggestions": true,
        "name": "prefer-enum-initializers",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce the use of Array.prototype.find() over Array.prototype.filter() followed by [0] when looking for a single result",
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-find"
        },
        "hasSuggestions": true,
        "name": "prefer-find",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce the use of `for-of` loop over the standard `for` loop where possible",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/prefer-for-of"
        },
        "name": "prefer-for-of",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce using function types instead of interfaces with call signatures",
          "recommended": "stylistic",
          "url": "https://typescript-eslint.io/rules/prefer-function-type"
        },
        "fixable": "code",
        "name": "prefer-function-type",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce `includes` method over `indexOf` method",
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-includes"
        },
        "fixable": "code",
        "name": "prefer-includes",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require all enum members to be literal values",
          "recommended": "strict",
          "requiresTypeChecking": false,
          "url": "https://typescript-eslint.io/rules/prefer-literal-enum-member"
        },
        "name": "prefer-literal-enum-member",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require using `namespace` keyword over `module` keyword to declare custom TypeScript modules",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/prefer-namespace-keyword"
        },
        "fixable": "code",
        "name": "prefer-namespace-keyword",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce using the nullish coalescing operator instead of logical assignments or chaining",
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-nullish-coalescing"
        },
        "hasSuggestions": true,
        "name": "prefer-nullish-coalescing",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce using concise optional chain expressions instead of chained logical ands, negated logical ors, or empty objects",
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-optional-chain"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "prefer-optional-chain",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require using Error objects as Promise rejection reasons",
          "extendsBaseRule": true,
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-promise-reject-errors"
        },
        "name": "prefer-promise-reject-errors",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require private members to be marked as `readonly` if they're never modified outside of the constructor",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-readonly"
        },
        "fixable": "code",
        "name": "prefer-readonly",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require function parameters to be typed as `readonly` to prevent accidental mutation of inputs",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-readonly-parameter-types"
        },
        "name": "prefer-readonly-parameter-types",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce using type parameter when calling `Array#reduce` instead of using a type assertion",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-reduce-type-parameter"
        },
        "fixable": "code",
        "name": "prefer-reduce-type-parameter",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Enforce `RegExp#exec` over `String#match` if no global flag is provided",
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-regexp-exec"
        },
        "fixable": "code",
        "name": "prefer-regexp-exec",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce that `this` is used when only `this` type is returned",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-return-this-type"
        },
        "fixable": "code",
        "name": "prefer-return-this-type",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce using `String#startsWith` and `String#endsWith` over other equivalent methods of checking substrings",
          "recommended": "stylistic",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/prefer-string-starts-ends-with"
        },
        "fixable": "code",
        "name": "prefer-string-starts-ends-with",
        "type": "suggestion"
      },
      {
        "deprecated": {
          "deprecatedSince": "7.11.0",
          "replacedBy": [
            {
              "rule": {
                "name": "@typescript-eslint/ban-ts-comment",
                "url": "https://typescript-eslint.io/rules/ban-ts-comment"
              }
            }
          ],
          "url": "https://github.com/typescript-eslint/typescript-eslint/pull/9081"
        },
        "docs": {
          "description": "Enforce using `@ts-expect-error` over `@ts-ignore`",
          "url": "https://typescript-eslint.io/rules/prefer-ts-expect-error"
        },
        "fixable": "code",
        "name": "prefer-ts-expect-error",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require any function or method that returns a Promise to be marked async",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/promise-function-async"
        },
        "fixable": "code",
        "name": "promise-function-async",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce that `get()` types should be assignable to their equivalent `set()` type",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/related-getter-setter-pairs"
        },
        "name": "related-getter-setter-pairs",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require `Array#sort` and `Array#toSorted` calls to always provide a `compareFunction`",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/require-array-sort-compare"
        },
        "name": "require-array-sort-compare",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow async functions which do not return promises and have no `await` expression",
          "extendsBaseRule": true,
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/require-await"
        },
        "hasSuggestions": true,
        "name": "require-await",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Require both operands of addition to be the same type and be `bigint`, `number`, or `string`",
          "recommended": {
            "recommended": true,
            "strict": [
              {
                "allowAny": false,
                "allowBoolean": false,
                "allowNullish": false,
                "allowNumberAndString": false,
                "allowRegExp": false
              }
            ]
          },
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/restrict-plus-operands"
        },
        "name": "restrict-plus-operands",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Enforce template literal expressions to be of `string` type",
          "recommended": {
            "recommended": true,
            "strict": [
              {
                "allowAny": false,
                "allowBoolean": false,
                "allowNever": false,
                "allowNullish": false,
                "allowNumber": false,
                "allowRegExp": false
              }
            ]
          },
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/restrict-template-expressions"
        },
        "name": "restrict-template-expressions",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Enforce consistent awaiting of returned promises",
          "recommended": {
            "strict": [
              "error-handling-correctness-only"
            ]
          },
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/return-await"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "return-await",
        "type": "problem"
      },
      {
        "deprecated": {
          "deprecatedSince": "7.13.0",
          "replacedBy": [
            {
              "plugin": {
                "name": "eslint-plugin-perfectionist",
                "url": "https://perfectionist.dev"
              },
              "rule": {
                "name": "perfectionist/sort-intersection-types",
                "url": "https://perfectionist.dev/rules/sort-intersection-types"
              }
            },
            {
              "plugin": {
                "name": "eslint-plugin-perfectionist",
                "url": "https://perfectionist.dev"
              },
              "rule": {
                "name": "perfectionist/sort-union-types",
                "url": "https://perfectionist.dev/rules/sort-union-types"
              }
            }
          ],
          "url": "https://github.com/typescript-eslint/typescript-eslint/pull/9253"
        },
        "docs": {
          "description": "Enforce constituents of a type union/intersection to be sorted alphabetically",
          "url": "https://typescript-eslint.io/rules/sort-type-constituents"
        },
        "fixable": "code",
        "hasSuggestions": true,
        "name": "sort-type-constituents",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow certain types in boolean expressions",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/strict-boolean-expressions"
        },
        "hasSuggestions": true,
        "name": "strict-boolean-expressions",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow passing a value-returning function in a position accepting a void function",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/strict-void-return"
        },
        "name": "strict-void-return",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Require switch-case statements to be exhaustive",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/switch-exhaustiveness-check"
        },
        "hasSuggestions": true,
        "name": "switch-exhaustiveness-check",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Disallow certain triple slash directives in favor of ES6-style import declarations",
          "recommended": "recommended",
          "url": "https://typescript-eslint.io/rules/triple-slash-reference"
        },
        "name": "triple-slash-reference",
        "type": "suggestion"
      },
      {
        "deprecated": {
          "deprecatedSince": "8.33.0",
          "message": "This is an old rule that is no longer recommended for use."
        },
        "docs": {
          "description": "Require type annotations in certain places",
          "url": "https://typescript-eslint.io/rules/typedef"
        },
        "name": "typedef",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce unbound methods are called with their expected scope",
          "recommended": "recommended",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/unbound-method"
        },
        "name": "unbound-method",
        "type": "problem"
      },
      {
        "docs": {
          "description": "Disallow two overloads that could be unified into one with a union or an optional/rest parameter",
          "recommended": "strict",
          "url": "https://typescript-eslint.io/rules/unified-signatures"
        },
        "name": "unified-signatures",
        "type": "suggestion"
      },
      {
        "docs": {
          "description": "Enforce typing arguments in Promise rejection callbacks as `unknown`",
          "recommended": "strict",
          "requiresTypeChecking": true,
          "url": "https://typescript-eslint.io/rules/use-unknown-in-catch-callback-variable"
        },
        "hasSuggestions": true,
        "name": "use-unknown-in-catch-callback-variable",
        "type": "suggestion"
      }
    ]
  },
  "favicon": "img/favicon.ico",
  "onBrokenAnchors": "ignore",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "organizationName": "typescript-eslint",
  "plugins": [
    "./plugins/recent-blog-posts/index.ts",
    [
      "docusaurus-plugin-typedoc",
      {
        "entryPoints": [
          "../ast-spec/src/index.ts"
        ],
        "enumMembersFormat": "table",
        "exclude": "**/*.d.ts",
        "excludeExternals": true,
        "groupOrder": [
          "Functions",
          "Variables",
          "*"
        ],
        "hidePageTitle": true,
        "id": "typedoc-generated-ast-spec",
        "indexFormat": "table",
        "out": "../../docs/packages/ast-spec/generated",
        "outputFileStrategy": "modules",
        "parametersFormat": "table",
        "plugin": [
          "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/tools/typedoc-plugin-no-inherit-fork.mjs"
        ],
        "propertiesFormat": "table",
        "readme": "none",
        "tsconfig": "../ast-spec/tsconfig.json",
        "typeDeclarationFormat": "table",
        "useCodeBlocks": true
      }
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        "entryPoints": [
          "../project-service/src/index.ts"
        ],
        "enumMembersFormat": "table",
        "exclude": "**/*.d.ts",
        "excludeExternals": true,
        "groupOrder": [
          "Functions",
          "Variables",
          "*"
        ],
        "hidePageTitle": true,
        "id": "typedoc-generated-project-service",
        "indexFormat": "table",
        "out": "../../docs/packages/project-service/generated",
        "outputFileStrategy": "modules",
        "parametersFormat": "table",
        "plugin": [
          "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/tools/typedoc-plugin-no-inherit-fork.mjs"
        ],
        "propertiesFormat": "table",
        "readme": "none",
        "tsconfig": "../project-service/tsconfig.json",
        "typeDeclarationFormat": "table",
        "useCodeBlocks": true
      }
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        "entryPoints": [
          "../rule-schema-to-typescript-types/src/index.ts"
        ],
        "enumMembersFormat": "table",
        "exclude": "**/*.d.ts",
        "excludeExternals": true,
        "groupOrder": [
          "Functions",
          "Variables",
          "*"
        ],
        "hidePageTitle": true,
        "id": "typedoc-generated-rule-schema-to-typescript-types",
        "indexFormat": "table",
        "out": "../../docs/packages/rule-schema-to-typescript-types/generated",
        "outputFileStrategy": "modules",
        "parametersFormat": "table",
        "plugin": [
          "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/tools/typedoc-plugin-no-inherit-fork.mjs"
        ],
        "propertiesFormat": "table",
        "readme": "none",
        "tsconfig": "../rule-schema-to-typescript-types/tsconfig.json",
        "typeDeclarationFormat": "table",
        "useCodeBlocks": true
      }
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        "entryPoints": [
          "../tsconfig-utils/src/index.ts"
        ],
        "enumMembersFormat": "table",
        "exclude": "**/*.d.ts",
        "excludeExternals": true,
        "groupOrder": [
          "Functions",
          "Variables",
          "*"
        ],
        "hidePageTitle": true,
        "id": "typedoc-generated-tsconfig-utils",
        "indexFormat": "table",
        "out": "../../docs/packages/tsconfig-utils/generated",
        "outputFileStrategy": "modules",
        "parametersFormat": "table",
        "plugin": [
          "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/tools/typedoc-plugin-no-inherit-fork.mjs"
        ],
        "propertiesFormat": "table",
        "readme": "none",
        "tsconfig": "../tsconfig-utils/tsconfig.json",
        "typeDeclarationFormat": "table",
        "useCodeBlocks": true
      }
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        "entryPoints": [
          "../type-utils/src/index.ts"
        ],
        "enumMembersFormat": "table",
        "exclude": "**/*.d.ts",
        "excludeExternals": true,
        "groupOrder": [
          "Functions",
          "Variables",
          "*"
        ],
        "hidePageTitle": true,
        "id": "typedoc-generated-type-utils",
        "indexFormat": "table",
        "out": "../../docs/packages/type-utils/generated",
        "outputFileStrategy": "modules",
        "parametersFormat": "table",
        "plugin": [
          "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/tools/typedoc-plugin-no-inherit-fork.mjs"
        ],
        "propertiesFormat": "table",
        "readme": "none",
        "tsconfig": "../type-utils/tsconfig.json",
        "typeDeclarationFormat": "table",
        "useCodeBlocks": true
      }
    ],
    "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/webpack.plugin.js",
    [
      "@docusaurus/plugin-content-docs",
      {
        "beforeDefaultRemarkPlugins": [
          null
        ],
        "breadcrumbs": false,
        "editUrl": "https://github.com/typescript-eslint/typescript-eslint/edit/main/packages/website/",
        "id": "base-docs",
        "path": "../../docs",
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "routeBasePath": "/",
        "sidebarPath": "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/sidebars/sidebar.base.js"
      }
    ],
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": true,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "queryString",
          "standalone"
        ],
        "pwaHead": [
          {
            "href": "/img/logo.svg",
            "rel": "icon",
            "tagName": "link"
          },
          {
            "href": "/manifest.json",
            "rel": "manifest",
            "tagName": "link"
          },
          {
            "content": "#443FD4",
            "name": "theme-color",
            "tagName": "meta"
          },
          {
            "content": "yes",
            "name": "apple-mobile-web-app-capable",
            "tagName": "meta"
          },
          {
            "content": "#443FD4",
            "name": "apple-mobile-web-app-status-bar-style",
            "tagName": "meta"
          },
          {
            "href": "/img/logo.png",
            "rel": "apple-touch-icon",
            "tagName": "link"
          },
          {
            "color": "#443FD4",
            "href": "/img/logo.png",
            "rel": "mask-icon",
            "tagName": "link"
          },
          {
            "content": "/img/logo.png",
            "name": "msapplication-TileImage",
            "tagName": "meta"
          },
          {
            "content": "#443FD4",
            "name": "msapplication-TileColor",
            "tagName": "meta"
          }
        ]
      }
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "from": "/docs",
            "to": "/getting-started"
          },
          {
            "from": "/getting-started/typed-linting/monorepos",
            "to": "/troubleshooting/typed-linting/monorepos"
          },
          {
            "from": "/linting/configs",
            "to": "/users/configs"
          },
          {
            "from": "/linting/troubleshooting",
            "to": "/troubleshooting/faqs/general"
          },
          {
            "from": "/linting/troubleshooting/formatting",
            "to": "/users/what-about-formatting"
          },
          {
            "from": "/linting/troubleshooting/typed-linting/Performance-troubleshooting",
            "to": "/troubleshooting/typed-linting/performance"
          },
          {
            "from": "/linting/troubleshooting/tslint",
            "to": "/users/what-about-tslint"
          },
          {
            "from": "/linting/typed-linting",
            "to": "/getting-started/typed-linting"
          },
          {
            "from": "/troubleshooting",
            "to": "/troubleshooting/faqs/general"
          },
          {
            "from": "/troubleshooting/faqs",
            "to": "/troubleshooting/faqs/general"
          },
          {
            "from": "/troubleshooting/formatting",
            "to": "/users/what-about-formatting"
          },
          {
            "from": "/troubleshooting/tslint",
            "to": "/users/what-about-tslint"
          },
          {
            "from": "/troubleshooting/performance-troubleshooting",
            "to": "/troubleshooting/typed-linting/performance"
          },
          {
            "from": "/linting/troubleshooting/typed-linting/Monorepos",
            "to": "/troubleshooting/typed-linting/monorepos"
          },
          {
            "from": "/maintenance/issues/rule-deprecations",
            "to": "/maintenance/issues/rule-deprecations-and-deletions"
          }
        ]
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "blog": {
          "blogSidebarCount": "ALL",
          "beforeDefaultRemarkPlugins": [
            null
          ],
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ]
          ]
        },
        "docs": {
          "beforeDefaultRemarkPlugins": [
            null
          ],
          "breadcrumbs": false,
          "editUrl": "https://github.com/typescript-eslint/typescript-eslint/edit/main/packages/website/",
          "exclude": [
            "TEMPLATE.md"
          ],
          "id": "rules-docs",
          "path": "../eslint-plugin/docs/rules",
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ]
          ],
          "routeBasePath": "rules",
          "sidebarPath": "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/sidebars/sidebar.rules.js"
        },
        "pages": {
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ]
          ]
        },
        "theme": {
          "customCss": "/Users/eceseckin/embed-analyzer/oss-pr-workspace/typescript-eslint-fork/packages/website/src/css/custom.css"
        }
      }
    ]
  ],
  "projectName": "typescript-eslint",
  "themeConfig": {
    "algolia": {
      "apiKey": "74d42ed10d0f7b327d74d774570035c7",
      "appId": "N1HUB2TU6A",
      "indexName": "typescript-eslint",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "footer": {
      "copyright": "Copyright © 2026 typescript-eslint, Inc. Built with Docusaurus.",
      "links": [
        {
          "items": [
            {
              "className": "image-link bluesky-link social-link-icon",
              "href": "https://bsky.app/profile/typescript-eslint.io",
              "label": "Bluesky",
              "rel": "me noopener"
            },
            {
              "className": "image-link discord-link social-link-icon",
              "href": "https://discord.gg/FSxKq8Tdyg",
              "label": "Discord",
              "rel": "noopener"
            },
            {
              "className": "image-link mastodon-link social-link-icon",
              "href": "https://fosstodon.org/@tseslint",
              "label": "Mastodon",
              "rel": "me noopener"
            },
            {
              "className": "image-link stack-overflow-link social-link-icon",
              "href": "https://stackoverflow.com/questions/tagged/typescript-eslint",
              "label": "Stack Overflow"
            }
          ],
          "title": "Community"
        },
        {
          "items": [
            {
              "className": "github-link image-link social-link-icon",
              "href": "https://github.com/typescript-eslint/typescript-eslint",
              "label": "GitHub",
              "rel": "me noopener"
            },
            {
              "className": "bug-report-link image-link social-link-icon",
              "href": "https://github.com/typescript-eslint/typescript-eslint/issues/new/choose",
              "label": "Report issue"
            },
            {
              "className": "open-collective-link image-link social-link-icon",
              "href": "https://opencollective.com/typescript-eslint/contribute",
              "label": "Open Collective"
            }
          ],
          "title": "More"
        }
      ],
      "logo": {
        "alt": "Deploys by Netlify",
        "href": "https://www.netlify.com",
        "src": "https://www.netlify.com/img/global/badges/netlify-dark.svg"
      },
      "style": "light"
    },
    "image": "img/logo-twitter-card.png",
    "metadata": [
      {
        "content": "#443fd4",
        "name": "msapplication-TileColor"
      },
      {
        "content": "#443fd4",
        "name": "theme-color"
      },
      {
        "content": "Typescript-eslint logo",
        "name": "twitter:image:alt"
      }
    ],
    "navbar": {
      "items": [
        {
          "label": "Docs",
          "position": "left",
          "to": "getting-started/"
        },
        {
          "label": "Rules",
          "position": "left",
          "to": "rules/"
        },
        {
          "label": "Blog",
          "position": "left",
          "to": "blog/"
        },
        {
          "href": "https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.60.0",
          "label": "v8.60.0",
          "position": "right"
        },
        {
          "activeBasePath": "play",
          "label": "Playground",
          "position": "right",
          "to": "play"
        },
        {
          "aria-label": "GitHub repository",
          "className": "github-link image-link header-image-link",
          "href": "https://github.com/typescript-eslint/typescript-eslint",
          "position": "right"
        },
        {
          "aria-label": "Discord",
          "className": "discord-link image-link header-image-link",
          "href": "https://discord.com/invite/FSxKq8Tdyg",
          "position": "right"
        }
      ],
      "logo": {
        "alt": "",
        "height": "32px",
        "src": "img/logo.svg",
        "width": "32px"
      },
      "title": "typescript-eslint",
      "hideOnScroll": false
    },
    "prism": {
      "additionalLanguages": [
        "bash",
        "diff",
        "ignore"
      ],
      "magicComments": [
        {
          "block": {
            "end": "highlight-end",
            "start": "highlight-start"
          },
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line"
        },
        {
          "block": {
            "end": "Removed lines end",
            "start": "Removed lines start"
          },
          "className": "code-block-removed-line",
          "line": "Remove this line"
        },
        {
          "block": {
            "end": "Added lines end",
            "start": "Added lines start"
          },
          "className": "code-block-added-line",
          "line": "Add this line"
        }
      ],
      "theme": {
        "plain": {},
        "styles": []
      }
    },
    "tableOfContents": {
      "maxHeadingLevel": 4,
      "minHeadingLevel": 2
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "stylesheets": [
    {
      "href": "/img/favicon/apple-touch-icon.png",
      "rel": "apple-touch-icon",
      "sizes": "180x180"
    },
    {
      "href": "/img/favicon/favicon-32x32.png",
      "rel": "icon",
      "sizes": "32x32",
      "type": "image/png"
    },
    {
      "href": "/img/favicon/favicon-16x16.png",
      "rel": "icon",
      "sizes": "16x16",
      "type": "image/png"
    },
    {
      "href": "/img/favicon/site.webmanifest",
      "rel": "manifest"
    },
    {
      "color": "#2656c7",
      "href": "/img/favicon/safari-pinned-tab.svg",
      "rel": "mask-icon"
    }
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
